### ISSUE TITLE
安装 (install)

### ISSUE THREAD

**Issue by china-enoch** [alicfeng/mysql_markdown#1]
我是 Mac 环境，不管我使用哪种安装方式，都会一直卡在某一个进度里面，导致我最终无法安装。我也尝试去 Google ，但是还是没有找到正确的答案。希望您能给予我帮助，下图是我分别使用两种安装方式遇到的情况及电脑系统版本信息。
![image](https://user-images.githubusercontent.com/16871710/69507850-081b1300-0f6f-11ea-8a66-dcf687a5b200.png)

**Comment by alicfeng** [comment]
不好意思，比较忙忘记回复了。从终端的信息来看，显而可以看出下载完成了但是解包过程中卡住了，执行安装脚本本质上就是从仓库拉取对应环境的可执行文件，也有可能是网络存在问题
1.在克隆仓库解压过程中多等一会，看看是否会成功
2.可以直接在仓库的release文件夹下载对应环境的程序文件，你的PC需要下载mysql_markdown_mac这个文件

**Comment by china-enoch** [comment]
我已经下载下来了，但是并不是我以为的 .dmg 格式的。我尝试打开它，却提示我这个错误。
![image](https://user-images.githubusercontent.com/16871710/69696888-0478bf00-111c-11ea-928c-a3e3c62eeaf8.png)
![image](https://user-images.githubusercontent.com/16871710/69696932-22462400-111c-11ea-9e6b-3785cc632340.png)

**Comment by alicfeng** [comment]
也许是我的说明文档没有很清晰地描述导致你理解错了。这个为已经编译完成的可执行二进制文件，可以直接通过终端运行，并非安装程序包( apk、dmg、exe )。

**Comment by china-enoch** [comment]
不好意思。回复您晚了。我赋予了那个文件可执行的权限，然后编译成功了。但是无论我使用哪个命令，都会 kill 掉 mysql_markdown 进程，而且随之又会有一个 mysql_markdown 的进程开启。所以就成了这种情况。您可以帮助我一下吗？
![image](https://user-images.githubusercontent.com/16871710/69898453-d651e400-1394-11ea-9caf-eca6f1533a58.png)

**Comment by alicfeng** [comment]
麻烦你将将编译的指令发出来一下。同时你在下载的文件夹下可以尝试一下如下指令
`cd release`
`chmod +x mysql_markdown_mac`
`./mysql_markdown_mac -v`

**Comment by china-enoch** [comment]
我是先赋予可运行的权限 755，然后直接在文件当前目录下执行 `./mysql_markdown_mac`
我把你的命令也在本机执行了一下，发现还是有提示的。是不是意味着每次我要执行命令的时候都得在文件当前目录下 `./mysql_markdown_mac -p xxx -d xxx` 呢？
![image](https://user-images.githubusercontent.com/16871710/69910371-5fc0ef00-1445-11ea-857a-2d25ab8ea376.png)

**Comment by china-enoch** [comment]
我这样子操作是可以的
![image](https://user-images.githubusercontent.com/16871710/69910399-d78f1980-1445-11ea-8057-81cd7b5df50f.png)

**Comment by alicfeng** [comment]
将程序放在环境变量的目录即可，比如放在`/usr/local/bin` 或者`/usr/sbin`就可以了，
`cp ./mysql_markdown_mac /usr/local/bin/mysql_markdown` 然后刷新终端会话就行了。
你之前说执行你构建的程序总是会被killed的麻烦发我一下，**a@samego.com**,Thanks♪(･ω･)ﾉ

**Comment by china-enoch** [comment]
我把我编译的过程已经邮件发您了。但是我按照您说的步骤去放到指定的目录，重新开启一个终端窗口。发现还是不可以。
![image](https://user-images.githubusercontent.com/16871710/69916089-683f1700-1491-11ea-8fd1-c50a0a1eac03.png)
![image](https://user-images.githubusercontent.com/16871710/69916094-72611580-1491-11ea-8d86-966cc051fb77.png)

**Comment by china-enoch** [comment]
按照您说的步骤，已经可以了。我把我编译的方式已经邮件发给您了。邮件后面说还是不可以，我发现等会儿就可以了。无论在哪个目录都是可以使用 mysql_markdown 的命令。非常感谢您的帮助。效果如下。再次感谢您。
![image](https://user-images.githubusercontent.com/16871710/69916161-704b8680-1492-11ea-86e6-abfb768d6efa.png)

![image](https://user-images.githubusercontent.com/16871710/69916159-6a55a580-1492-11ea-8201-c01271d6f26c.png)

**Comment by alicfeng** [comment]
好的好的，客气了😄



    
    
        
            
                
                    
                        
                    
                    
                        
                            AlicFeng
                            
                                    
                                    SameGo
                                  
                                     - 
                                    Technical Leader
                            
                                
                                    邮箱：a@samego.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


            在2019年12月01日 23:30，Mr.wang 写道： 按照您说的步骤，已经可以了。我把我编译的方式已经邮件发给您了。邮件后面说还是不可以，我发现等会儿就可以了。无论在哪个目录都是可以使用 mysql_markdown 的命令。非常感谢您的帮助。效果如下。再次感谢您。







—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/alicfeng/mysql_markdown/issues/1?email_source=notifications\u0026email_token=AGXUOT3SVQVDPP433ODG4ZDQWPJ7HA5CNFSM4JRCQ5GKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFRMMGI#issuecomment-560121369",

"url": "https://github.com/alicfeng/mysql_markdown/issues/1?email_source=notifications\u0026email_token=AGXUOT3SVQVDPP433ODG4ZDQWPJ7HA5CNFSM4JRCQ5GKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFRMMGI#issuecomment-560121369",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
